version: "3"

services:
    mysql:
        build: ./dockerfiles/mysql
        ports:
            - "33069:3306"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: pereira
            MYSQL_DATABASE: blog
volumes:
    mysql-data:
        driver: "local"
