version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=pereira
      - MYSQL_PASSWORD=16022004
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
